import { useState, useEffect } from "react";
import { Download, AlertCircle, CheckCircle, BrainCircuit } from "lucide-react";
import { callGeminiAPI } from "../utils/gemini";
import { LoadingSkeleton } from "./LoadingSkeleton";

export const Dashboard = ({ symptomResults, diabetesResults }) => {
  const [recommendation, setRecommendation] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const hasData = symptomResults && symptomResults.length > 0 && diabetesResults;

  useEffect(() => {
    if (hasData && !recommendation && !isLoading) {
      generateCompositeRecommendation();
    }
  }, [hasData]);

  const generateCompositeRecommendation = async () => {
    setIsLoading(true);
    const topDisease = symptomResults[0];
    
    const prompt = `A user has done two health checks. 
1) Symptom prediction: Most likely condition is ${topDisease.name} with ${topDisease.confidence}% confidence. 
2) Diabetes Risk Score is ${diabetesResults.score}/100 (${diabetesResults.label}). 
Provide a composite health recommendation based on both results combined. Respond in exactly this JSON format:
{
  "summary": "1-2 sentence overall summary",
  "priority": "what they should focus on first",
  "nextStep": "the single most important actionable step"
}`;

    const fallback = {
      summary: "Your health results show elevated risk factors requiring attention.",
      priority: "Address the acute symptoms while managing your lifestyle risk factors.",
      nextStep: "Schedule an appointment with a primary care physician to review these findings."
    };

    const result = await callGeminiAPI(prompt, fallback);
    setRecommendation(result);
    setIsLoading(false);
  };

  const handleDownload = () => {
    const topDisease = symptomResults?.[0];
    
    let content = `=============================\n`;
    content += `SYMPTOMSENSE AI HEALTH REPORT\n`;
    content += `=============================\n\n`;
    
    if (topDisease) {
      content += `[ SYMPTOM CHECK ]\n`;
      content += `Top Match: ${topDisease.name} (${topDisease.confidence}% confidence)\n`;
      content += `Severity: ${topDisease.severity.toUpperCase()}\n`;
      content += `Specialist Needed: ${topDisease.specialist}\n\n`;
    }
    
    if (diabetesResults) {
      content += `[ DIABETES RISK CHECK ]\n`;
      content += `Score: ${diabetesResults.score}/100\n`;
      content += `Risk Level: ${diabetesResults.label}\n\n`;
    }
    
    if (recommendation) {
      content += `[ AI OVERALL RECOMMENDATION ]\n`;
      content += `Summary: ${recommendation.summary}\n`;
      content += `Priority: ${recommendation.priority}\n`;
      content += `Crucial Next Step: ${recommendation.nextStep}\n\n`;
    }
    
    content += `DISCLAIMER: This report is generated by AI and is not a substitute for professional medical advice.`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "health_report.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!hasData) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] text-center space-y-4">
        <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center animate-pulse">
          <AlertCircle size={40} className="text-slate-500" />
        </div>
        <h2 className="text-2xl font-bold text-white">Incomplete Health Profile</h2>
        <p className="text-slate-400 max-w-md">
          Please complete both the "Symptom Checker" and the "Diabetes Risk" assessments to view your comprehensive AI health dashboard.
        </p>
      </div>
    );
  }

  // Calculate composite 'Health Score' inverted from risks
  const symptomRiskPenalty = symptomResults[0].confidence * (symptomResults[0].severity === 'severe' ? 0.8 : 0.4);
  const diabetesRiskPenalty = diabetesResults.score * 0.5;
  const healthScore = Math.max(0, Math.round(100 - ((symptomRiskPenalty + diabetesRiskPenalty) / 2)));
  
  let scoreColor = "text-emerald-400";
  if (healthScore < 50) scoreColor = "text-red-400";
  else if (healthScore < 75) scoreColor = "text-yellow-400";

  return (
    <div className="space-y-6 pb-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8 relative z-10">
        <div>
          <h2 className="text-2xl font-headline font-bold text-white tracking-tight">Comprehensive Dashboard</h2>
          <p className="text-slate-400 text-sm mt-1">Your synthesized health metrics and AI guidance.</p>
        </div>
        <button 
          onClick={handleDownload}
          disabled={isLoading}
          className="flex items-center gap-3 font-headline px-6 py-3 bg-gradient-to-r from-primary to-primary-container text-[#00354a] font-bold rounded-xl hover-lift active:scale-95 disabled:opacity-50"
        >
          <Download size={18} /> Download Full Report
        </button>
      </div>

      <div className="grid md:grid-cols-3 gap-6 relative z-10">
        {/* Composite Health Score */}
        <div className="glass-card hover-lift p-6 rounded-3xl border-l-[6px] border-l-primary flex flex-col items-center justify-center text-center shadow-lg relative overflow-hidden animate-fade-up stagger-1">
          <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none select-none">
            <span className="text-6xl font-headline font-black text-white">HEALTH</span>
          </div>
          <h3 className="text-slate-400 font-label text-[10px] uppercase tracking-[0.2em] mb-4">Overall Wellness Score</h3>
          <div className={`text-6xl font-headline font-black ${scoreColor} mb-2 drop-shadow-[0_0_12px_rgba(currentColor,0.4)]`}>{healthScore}</div>
          <p className="text-xs text-slate-500 relative z-10">Derived from symptom severity and diabetes risk</p>
        </div>

        {/* Tab 1 Summary */}
        <div className="glass-card hover-lift p-6 rounded-3xl border-l-4 border-l-sky-400 relative overflow-hidden animate-fade-up stagger-2">
           <div className="flex justify-between items-start mb-4">
             <span className="material-symbols-outlined text-sky-400">medical_services</span>
             <span className="text-[10px] text-slate-500 font-label tracking-widest">SYMPTOM RISK</span>
           </div>
           <h4 className="text-white font-headline text-xl font-bold mb-1 leading-tight">
             {symptomResults[0].name}
           </h4>
           <div className="mt-1 text-sky-400 text-sm font-bold uppercase tracking-wider">
             {symptomResults[0].confidence}% Confidence Match
           </div>
           <div className="mt-4 inline-block px-3 py-1.5 bg-surface-container-low border border-white/5 rounded-full text-xs font-semibold text-slate-300 shadow-inner">
             Specialist: {symptomResults[0].specialist}
           </div>
        </div>

        {/* Tab 2 Summary */}
        <div className="glass-card hover-lift p-6 rounded-3xl border-l-4 border-l-tertiary relative overflow-hidden animate-fade-up stagger-3">
           <div className="flex justify-between items-start mb-4">
             <span className="material-symbols-outlined text-tertiary">warning</span>
             <span className="text-[10px] text-slate-500 font-label tracking-widest">DIABETES RISK</span>
           </div>
           <h4 className="text-white font-headline text-xl font-bold mb-1">
             Score: {diabetesResults.score}/100
           </h4>
           <div className={`mt-1 ${diabetesResults.color} text-sm font-bold uppercase tracking-wider mb-3`}>
             {diabetesResults.label}
           </div>
           <div className="w-full h-1.5 bg-white/5 rounded-full overflow-hidden">
             <div className="h-full bg-tertiary neon-glow" style={{ width: `${diabetesResults.score}%` }}></div>
           </div>
        </div>
      </div>

      {isLoading && <LoadingSkeleton />}

      {recommendation && !isLoading && (
        <div className="glass-card mt-8 p-6 md:p-8 rounded-3xl relative overflow-hidden group animate-fade-up">
          <div className="absolute inset-0 scanline opacity-30 pointer-events-none"></div>
          
          <h3 className="text-2xl font-headline font-bold text-white mb-6 flex items-center gap-3 relative z-10">
             <span className="material-symbols-outlined text-primary text-3xl">psychology</span>
             AI Synthesis & Recommendations
          </h3>

          <div className="space-y-6 relative z-10">
            <div>
              <h4 className="text-sky-400 font-label font-bold mb-2 uppercase text-xs tracking-[0.2em]">Executive Summary</h4>
              <p className="text-slate-200 text-sm md:text-base leading-relaxed bg-surface-container-low p-5 rounded-2xl border border-white/5">
                {recommendation.summary}
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 gap-6 mt-4">
               <div>
                  <h4 className="text-tertiary font-label font-bold mb-2 uppercase text-xs tracking-[0.2em]">Immediate Priority</h4>
                  <div className="bg-surface-container-low p-5 rounded-2xl border border-white/5 text-slate-300 text-sm h-full flex items-center">
                    {recommendation.priority}
                  </div>
               </div>
               <div>
                  <h4 className="text-emerald-400 font-label font-bold mb-2 uppercase text-xs tracking-[0.2em]">Crucial Next Step</h4>
                  <div className="bg-surface-container-low p-5 rounded-2xl border border-emerald-500/20 text-slate-300 text-sm h-full flex items-center gap-3">
                    <span className="material-symbols-outlined text-emerald-500 bg-emerald-500/10 p-2 rounded-full">check_circle</span>
                    {recommendation.nextStep}
                  </div>
               </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
