import { useState, useEffect } from "react";
import { Download, AlertCircle, CheckCircle, BrainCircuit } from "lucide-react";
import { callGeminiAPI } from "../utils/gemini";
import { LoadingSkeleton } from "./LoadingSkeleton";

export const Dashboard = ({ symptomResults, diabetesResults }) => {
  const [recommendation, setRecommendation] = useState(null);
  const [isLoading, setIsLoading] = useState(false);

  const hasData = symptomResults && symptomResults.length > 0 && diabetesResults;

  useEffect(() => {
    if (hasData && !recommendation && !isLoading) {
      generateCompositeRecommendation();
    }
  }, [hasData]);

  const generateCompositeRecommendation = async () => {
    setIsLoading(true);
    const topDisease = symptomResults[0];
    
    const prompt = `A user has done two health checks. 
1) Symptom prediction: Most likely condition is ${topDisease.name} with ${topDisease.confidence}% confidence. 
2) Diabetes Risk Score is ${diabetesResults.score}/100 (${diabetesResults.label}). 
Provide a composite health recommendation based on both results combined. Respond in exactly this JSON format:
{
  "summary": "1-2 sentence overall summary",
  "priority": "what they should focus on first",
  "nextStep": "the single most important actionable step"
}`;

    const fallback = {
      summary: "Your health results show elevated risk factors requiring attention.",
      priority: "Address the acute symptoms while managing your lifestyle risk factors.",
      nextStep: "Schedule an appointment with a primary care physician to review these findings."
    };

    const result = await callGeminiAPI(prompt, fallback);
    setRecommendation(result);
    setIsLoading(false);
  };

  const handleDownload = () => {
    const topDisease = symptomResults?.[0];
    
    let content = `=============================\n`;
    content += `SYMPTOMSENSE AI HEALTH REPORT\n`;
    content += `=============================\n\n`;
    
    if (topDisease) {
      content += `[ SYMPTOM CHECK ]\n`;
      content += `Top Match: ${topDisease.name} (${topDisease.confidence}% confidence)\n`;
      content += `Severity: ${topDisease.severity.toUpperCase()}\n`;
      content += `Specialist Needed: ${topDisease.specialist}\n\n`;
    }
    
    if (diabetesResults) {
      content += `[ DIABETES RISK CHECK ]\n`;
      content += `Score: ${diabetesResults.score}/100\n`;
      content += `Risk Level: ${diabetesResults.label}\n\n`;
    }
    
    if (recommendation) {
      content += `[ AI OVERALL RECOMMENDATION ]\n`;
      content += `Summary: ${recommendation.summary}\n`;
      content += `Priority: ${recommendation.priority}\n`;
      content += `Crucial Next Step: ${recommendation.nextStep}\n\n`;
    }
    
    content += `DISCLAIMER: This report is generated by AI and is not a substitute for professional medical advice.`;

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "health_report.txt";
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (!hasData) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[50vh] text-center space-y-4">
        <div className="w-20 h-20 bg-slate-800 rounded-full flex items-center justify-center animate-pulse">
          <AlertCircle size={40} className="text-slate-500" />
        </div>
        <h2 className="text-2xl font-bold text-white">Incomplete Health Profile</h2>
        <p className="text-slate-400 max-w-md">
          Please complete both the "Symptom Checker" and the "Diabetes Risk" assessments to view your comprehensive AI health dashboard.
        </p>
      </div>
    );
  }

  // Calculate composite 'Health Score' inverted from risks
  const symptomRiskPenalty = symptomResults[0].confidence * (symptomResults[0].severity === 'severe' ? 0.8 : 0.4);
  const diabetesRiskPenalty = diabetesResults.score * 0.5;
  const healthScore = Math.max(0, Math.round(100 - ((symptomRiskPenalty + diabetesRiskPenalty) / 2)));
  
  let scoreColor = "text-emerald-400";
  if (healthScore < 50) scoreColor = "text-red-400";
  else if (healthScore < 75) scoreColor = "text-yellow-400";

  return (
    <div className="space-y-6 pb-8">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 mb-8">
        <div>
          <h2 className="text-2xl font-bold text-white">Comprehensive Dashboard</h2>
          <p className="text-slate-400 font-medium mt-1">Your synthesized health metrics and AI guidance.</p>
        </div>
        <button 
          onClick={handleDownload}
          disabled={isLoading}
          className="flex items-center gap-2 px-5 py-2.5 bg-indigo-500 hover:bg-indigo-400 text-white font-semibold rounded-xl transition-colors shadow-lg shadow-indigo-500/20 disabled:opacity-50"
        >
          <Download size={18} /> Download Full Report
        </button>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        {/* Composite Health Score */}
        <div className="bg-slate-800/80 rounded-2xl p-6 border border-slate-700 flex flex-col items-center justify-center text-center shadow-lg">
          <h3 className="text-slate-400 font-medium mb-4">Overall Wellness Score</h3>
          <div className={`text-6xl font-black ${scoreColor} mb-2`}>{healthScore}</div>
          <p className="text-sm text-slate-500">Derived from symptom severity and diabetes risk</p>
        </div>

        {/* Tab 1 Summary */}
        <div className="bg-slate-800/50 rounded-2xl p-6 border border-slate-700">
           <h3 className="font-semibold text-slate-300 mb-4 flex items-center gap-2 border-b border-slate-700 pb-2">
             <AlertCircle size={16} className="text-sky-400"/> Primary Symptom Risk
           </h3>
           <div className="text-2xl font-bold text-white leading-tight">
             {symptomResults[0].name}
           </div>
           <div className="mt-2 text-sky-400 font-medium">
             {symptomResults[0].confidence}% Confidence Match
           </div>
           <div className="mt-3 inline-block px-2 py-1 bg-slate-900 rounded-md text-xs font-semibold text-slate-300">
             Specialist: {symptomResults[0].specialist}
           </div>
        </div>

        {/* Tab 2 Summary */}
        <div className="bg-slate-800/50 rounded-2xl p-6 border border-slate-700">
           <h3 className="font-semibold text-slate-300 mb-4 flex items-center gap-2 border-b border-slate-700 pb-2">
             <CheckCircle size={16} className="text-emerald-400"/> Diabetes Risk Indicator
           </h3>
           <div className={`text-3xl font-bold ${diabetesResults.color} leading-tight`}>
             {diabetesResults.score}/100
           </div>
           <div className="mt-2 text-slate-300 font-medium">
             Level: <span className={diabetesResults.color}>{diabetesResults.label}</span>
           </div>
        </div>
      </div>

      <div className="border-t border-slate-800 my-8 pt-8" />

      {isLoading && <LoadingSkeleton />}

      {recommendation && !isLoading && (
        <div className="bg-gradient-to-br from-indigo-900/30 to-purple-900/30 border border-indigo-800/50 rounded-3xl p-8 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-500/10 rounded-full blur-3xl -mr-20 -mt-20 pointer-events-none" />
          
          <h3 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
             <BrainCircuit size={28} className="text-indigo-400" />
             AI Synthesis & Recommendations
          </h3>

          <div className="space-y-6 relative z-10">
            <div>
              <h4 className="text-indigo-300 font-semibold mb-2 uppercase text-sm tracking-wider">Executive Summary</h4>
              <p className="text-slate-200 text-lg leading-relaxed bg-slate-900/40 p-4 rounded-xl border border-slate-800/50">
                {recommendation.summary}
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 gap-6 mt-4">
               <div>
                  <h4 className="text-purple-300 font-semibold mb-2 uppercase text-sm tracking-wider">Immediate Priority</h4>
                  <div className="bg-slate-900/40 p-4 rounded-xl border border-slate-800/50 text-slate-300 h-full">
                    {recommendation.priority}
                  </div>
               </div>
               <div>
                  <h4 className="text-pink-300 font-semibold mb-2 uppercase text-sm tracking-wider">Crucial Next Step</h4>
                  <div className="bg-slate-900/40 p-4 rounded-xl border border-slate-800/50 text-slate-300 h-full">
                    <span className="flex items-center gap-2">
                       <CheckCircle size={18} className="text-pink-500" />
                       {recommendation.nextStep}
                    </span>
                  </div>
               </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
